# Generated by Django 3.0.2 on 2020-01-22 21:51

import apps.usuario.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuario', models.CharField(max_length=15, unique=True, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Correo Electronico')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-is_active'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.Usuario')),
                ('roles', models.CharField(choices=[('1', 'Administrador'), ('2', 'Usuario'), ('3', 'Personal'), ('4', 'Gerente'), ('5', 'Gerente de ventas'), ('6', 'Representante de ventas')], default='Usuario', max_length=20)),
                ('perfil_img', models.ImageField(blank=True, null=True, upload_to=apps.usuario.models.img_url, verbose_name='Imagen de Perfil')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
                'ordering': ['-is_active'],
            },
            bases=('usuario.usuario',),
        ),
    ]
